name: Download NammaYatri Stats

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["DataURLs.txt"]
  schedule:
    - cron:  '29 18 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  download-json-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      
    - name: Download JSON files
      run: |
        mkdir -p raw-data  # Creates a directory named "raw-data" if it doesn't exist
        while IFS= read -r url; do  # Reads each line (URL) from the file "DataURLs.txt"
          echo "$url"  # Outputs the URL being processed
          filename=$(basename "$url")  # Extracts the filename from the URL
          folder=$(dirname "$url")  # Extracts the folder path from the URL
          mkdir -p "raw-data/$folder"  # Creates the folder structure in "raw-data"
          curl -L "$url" -o "raw-data/$folder/$filename"  # Downloads the file using curl and saves it with the same filename into the corresponding folder in the "raw-data" directory
        done < DataURLs.txt  # Specifies the file from which to read the URLs

    
    - name: Extract Reviews
      run: |
        mkdir -p raw-data/reviews
        cd script
        python ExtractReviews.py
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Add new JSON files"
        commit_options: '--no-verify'
        file_pattern: 'raw-data/*.json raw-data/reviews/*.json'
